# Your .github/workflows/coverity.yml file.
name: Coverity scan

# We only want to test official release code, not every pull request.
on:
  push:
    branches: [master]

jobs:
  coverity:
    runs-on: ubuntu-24.04
    if: github.repository == 'SIPp/sipp'
    steps:
    - uses: actions/checkout@v6
    - run: sudo apt update
    - run: sudo apt-get install --yes build-essential cmake libpcap-dev openssl libssl-dev libgsl-dev libsctp-dev libncurses-dev libncurses6
    - run:  cmake . -DUSE_GSL=1 -DUSE_PCAP=1 -DUSE_SCTP=1
    - uses: vapier/coverity-scan-action@v1
      with:
        email: ${{ secrets.COVERITY_SCAN_EMAIL }}
        token: ${{ secrets.COVERITY_SCAN_TOKEN }}
